name: ompi_NVIDIA CI
on: [pull_request]
jobs:

  nvidia_deployment:
    if: github.repository == 'open-mpi/ompi'
    runs-on: [self-hosted, linux, x64, nvidia]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout CI scripts
      uses: actions/checkout@v4
      with:
        repository: Mellanox/jenkins_scripts
        path: ompi_ci
    - name: Deployment infrastructure
      run: /start deploy
  nvidia_build:
    needs: [nvidia_deployment]
    runs-on: [self-hosted, linux, x64, nvidia]
    steps:
    - name: Building OMPI,UCX and tests
      run: /start build
  nvidia_test:
    needs: [nvidia_deployment, nvidia_build]
    runs-on: [self-hosted, linux, x64, nvidia]
    steps:
    - name: Running tests
      run: /start test
  nvidia_clean:
# always() should be used to run "clean" even when the workflow was canceled
#  ( in case of the right repository name)
# The second condition doesn't work when the workflow was canceled

    if: always() && (github.repository == 'open-mpi/ompi')
    needs: [nvidia_deployment, nvidia_build, nvidia_test]
    runs-on: [self-hosted, linux, x64, nvidia]
    steps:
    - name: Cleaning
      run: /start clean
